export const TRAER_PRODUCTOS = "TRAER_PRODUCTOS";
export const SET_PAGINA = "SET_PAGINA";
export const BUSCAR_PRUDUCTOS = "BUSCAR_PRUDUCTOS";
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";
export const FILTER_CATEGORIA = "FILTER_CATEGORIA";
export const SET_ORDER = "SET_ORDER";
