export const TRAER_PRODUCTOS = 'TRAER_PRODUCTOS';
export const SET_PAGINA = 'SET_PAGINA';
export const BUSCAR_PRUDUCTOS = 'BUSCAR_PRUDUCTOS';
export const AGREGAR_CARRITO = 'AGREGAR_CARRITO';
export const QUITAR_CARRITO = 'QUITAR_CARRITO';

