
export const TRAER_PRODUCTOS = "TRAER_PRODUCTOS";
export const SET_PAGINA = "SET_PAGINA";
export const BUSCAR_PRUDUCTOS = "BUSCAR_PRUDUCTOS";
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";
export const FILTER_CATEGORIA = "FILTER_CATEGORIA";
export const SET_ORDER = "SET_ORDER";
export const AGREGAR_CARRITO = 'AGREGAR_CARRITO';
export const QUITAR_CARRITO = 'QUITAR_CARRITO';
export const CARGAR_CARRITO = 'CARGAR_CARRITO';
export const SET_INICIO_SESION = 'SET_INICIO_SESION';

